In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df_biketrips = pd.read_csv('biketrips2011.csv')
df_biketrips['StartTime'] = df_biketrips['StartTime'].astype('datetime64')
df_biketrips['EndTime'] = df_biketrips['EndTime'].astype('datetime64')

group_startloc = df_biketrips.groupby('StartNum')
group_startloc_byhour = df_biketrips.groupby(['StartNum',pd.TimeGrouper('H',key='StartTime')])

group_endloc = df_biketrips.groupby('EndNum')
group_startloc_byhour = df_biketrips.groupby(['StartNum',pd.TimeGrouper('H',key='EndTime')])

In [32]:
#find busiest hour at location
group_startloc_bydate.sum()['count'].sort_values(ascending=False).head(50)

StartNum  StartTime
31200.0   2011-05-29 12:00:00    39
          2011-08-07 12:00:00    38
          2011-08-30 18:00:00    38
          2011-06-07 18:00:00    38
31235.0   2011-10-08 15:00:00    37
31200.0   2011-10-18 18:00:00    36
          2011-06-28 18:00:00    36
31219.0   2011-07-04 16:00:00    36
31200.0   2011-06-26 12:00:00    36
31217.0   2011-04-03 14:00:00    35
          2011-07-04 21:00:00    35
31200.0   2011-10-09 12:00:00    34
31205.0   2011-10-25 18:00:00    34
31200.0   2011-09-04 12:00:00    34
31623.0   2011-09-12 17:00:00    33
31200.0   2011-09-10 17:00:00    33
          2011-08-11 18:00:00    33
          2011-06-13 18:00:00    33
          2011-04-30 12:00:00    33
          2011-07-14 18:00:00    32
31261.0   2011-09-22 19:00:00    32
31200.0   2011-08-29 18:00:00    32
31219.0   2011-10-10 16:00:00    32
31217.0   2011-11-25 16:00:00    32
31200.0   2011-09-25 12:00:00    32
          2011-05-24 17:00:00    32
31219.0   2011-05-21 15:00:00    32
31200.0   2011-08-09 18:00:00    32
          2011-05-19 18:00:00    32
          2011-09-18 13:00:00    32
          2011-05-10 18:00:00    31
31623.0   2011-06-29 18:00:00    31
31200.0   2011-07-16 13:00:00    31
          2011-06-30 18:00:00    31
          2011-09-11 19:00:00    31
31217.0   2011-04-23 15:00:00    31
31200.0   2011-10-25 18:00:00    31
          2011-07-27 17:00:00    31
31217.0   2011-10-08 17:00:00    31
31200.0   2011-07-19 18:00:00    30
          2011-05-03 18:00:00    30
31217.0   2011-10-09 17:00:00    30
31623.0   2011-06-22 18:00:00    30
31200.0   2011-06-24 18:00:00    30
31217.0   2011-10-09 16:00:00    30
          2011-09-04 15:00:00    30
31235.0   2011-07-04 21:00:00    30
31200.0   2011-11-06 11:00:00    30
31623.0   2011-09-01 08:00:00    30
31200.0   2011-05-26 19:00:00    30
Name: count, dtype: int64

In [35]:
#find busiest days in 2011 at busiest location
group_startloc.get_group(31200).groupby(pd.TimeGrouper('D',key='StartTime')).count()['count'].sort_values(ascending=False).head(50)

StartTime
2011-07-16    275
2011-06-04    275
2011-09-10    268
2011-10-09    258
2011-06-29    248
2011-06-05    247
2011-04-30    246
2011-09-25    241
2011-09-24    241
2011-05-29    240
2011-07-17    239
2011-07-31    235
2011-07-14    235
2011-06-26    233
2011-08-20    229
2011-09-04    229
2011-08-26    228
2011-05-21    225
2011-10-15    225
2011-10-16    225
2011-08-30    224
2011-06-28    224
2011-06-13    222
2011-08-31    221
2011-06-30    221
2011-06-03    221
2011-05-28    221
2011-07-10    220
2011-08-23    219
2011-09-13    219
2011-06-21    217
2011-05-08    216
2011-06-25    215
2011-05-10    214
2011-10-25    214
2011-06-14    213
2011-09-11    212
2011-08-28    212
2011-06-12    210
2011-08-02    209
2011-10-18    208
2011-07-09    208
2011-06-07    208
2011-07-15    207
2011-05-19    207
2011-09-22    205
2011-06-23    205
2011-08-11    204
2011-10-10    204
2011-05-15    204
Name: count, dtype: int64

In [46]:
group_startloc.get_group(31200).groupby(pd.TimeGrouper('M',key='StartTime')).count()

,Unnamed: 0,BikeNum,MemType,StartNum,EndNum,LastEnd,EndTime,LastEndTime,count,TripDuration,...,bikeavailunder1m,bikeavailunder10m,bikeavailunder1h,bikeavailover12h,bikeavailover1d,biketripunder1m,biketripunder10m,biketripunder1h,biketripover1h,biketripover1d
StartTime,,,,,,,,,,,,,,,,,,,,,
2011-01-31,1367,1367,1367,1367,1367,1356,1367,1356,1367,1367,...,1367,1367,1367,1367,1367,1367,1367,1367,1367,1367
2011-02-28,1617,1617,1617,1617,1617,1614,1617,1614,1617,1617,...,1617,1617,1617,1617,1617,1617,1617,1617,1617,1617
2011-03-31,2259,2259,2259,2259,2259,2256,2259,2256,2259,2259,...,2259,2259,2259,2259,2259,2259,2259,2259,2259,2259
2011-04-30,3466,3466,3466,3466,3466,3466,3466,3466,3466,3466,...,3466,3466,3466,3466,3466,3466,3466,3466,3466,3466
2011-05-31,5644,5644,5644,5644,5644,5644,5644,5644,5644,5644,...,5644,5644,5644,5644,5644,5644,5644,5644,5644,5644
2011-06-30,6041,6041,6041,6041,6041,6041,6041,6041,6041,6041,...,6041,6041,6041,6041,6041,6041,6041,6041,6041,6041
2011-07-31,5694,5694,5694,5694,5694,5694,5694,5694,5694,5694,...,5694,5694,5694,5694,5694,5694,5694,5694,5694,5694
2011-08-31,5648,5648,5648,5648,5648,5648,5648,5648,5648,5648,...,5648,5648,5648,5648,5648,5648,5648,5648,5648,5648
2011-09-30,5277,5277,5277,5277,5277,5277,5277,5277,5277,5277,...,5277,5277,5277,5277,5277,5277,5277,5277,5277,5277
2011-10-31,5021,5021,5021,5021,5021,5021,5021,5021,5021,5021,...,5021,5021,5021,5021,5021,5021,5021,5021,5021,5021
2011-11-30,4061,4061,4061,4061,4061,4061,4061,4061,4061,4061,...,4061,4061,4061,4061,4061,4061,4061,4061,4061,4061
2011-12-31,2998,2998,2998,2998,2998,2998,2998,2998,2998,2998,...,2998,2998,2998,2998,2998,2998,2998,2998,2998,2998

In [47]:
group_endloc.get_group(31200).groupby(pd.TimeGrouper('M',key='EndTime')).count()

,Unnamed: 0,BikeNum,MemType,StartNum,EndNum,LastEnd,StartTime,LastEndTime,count,TripDuration,...,bikeavailunder1m,bikeavailunder10m,bikeavailunder1h,bikeavailover12h,bikeavailover1d,biketripunder1m,biketripunder10m,biketripunder1h,biketripover1h,biketripover1d
EndTime,,,,,,,,,,,,,,,,,,,,,
2011-01-31,1597,1597,1597,1597,1597,1582,1597,1582,1597,1597,...,1597,1597,1597,1597,1597,1597,1597,1597,1597,1597
2011-02-28,1867,1867,1867,1867,1867,1866,1867,1866,1867,1867,...,1867,1867,1867,1867,1867,1867,1867,1867,1867,1867
2011-03-31,2622,2622,2622,2622,2622,2618,2622,2618,2622,2622,...,2622,2622,2622,2622,2622,2622,2622,2622,2622,2622
2011-04-30,3914,3914,3914,3914,3914,3911,3914,3911,3914,3914,...,3914,3914,3914,3914,3914,3914,3914,3914,3914,3914
2011-05-31,6068,6068,6068,6068,6068,6068,6068,6068,6068,6068,...,6068,6068,6068,6068,6068,6068,6068,6068,6068,6068
2011-06-30,6538,6538,6538,6538,6538,6538,6538,6538,6538,6538,...,6538,6538,6538,6538,6538,6538,6538,6538,6538,6538
2011-07-31,6046,6046,6046,6046,6046,6046,6046,6046,6046,6046,...,6046,6046,6046,6046,6046,6046,6046,6046,6046,6046
2011-08-31,5941,5941,5941,5941,5941,5941,5941,5941,5941,5941,...,5941,5941,5941,5941,5941,5941,5941,5941,5941,5941
2011-09-30,5624,5624,5624,5624,5624,5624,5624,5624,5624,5624,...,5624,5624,5624,5624,5624,5624,5624,5624,5624,5624
2011-10-31,5561,5561,5561,5561,5561,5561,5561,5561,5561,5561,...,5561,5561,5561,5561,5561,5561,5561,5561,5561,5561
2011-11-30,4583,4583,4583,4583,4583,4582,4583,4582,4583,4583,...,4583,4583,4583,4583,4583,4583,4583,4583,4583,4583
2011-12-31,3549,3549,3549,3549,3549,3541,3549,3541,3549,3549,...,3549,3549,3549,3549,3549,3549,3549,3549,3549,3549